### ISSUE TITLE
Can Item Type ID, custom field name, type and value be removed?

### ISSUE THREAD

**Issue by quinone** [quinone/password-manager#28]
I'm not sure what the purpose of these fields are here? 
Do we need them currently? 
![image](https://github.com/quinone/password-manager/assets/29272824/06dd72dd-fd4a-4134-b58f-90a5ec15dbc6)

**Comment by Rachie94** [comment]
I wouldn't say so. They didn't make much sense to me. Just username password folder maybe what it is like social media, banking etc and url?

**Comment by Pitoche** [comment]
Well, Those are the Items that will be used to create instances on the vault. 
This is a pure copy of Bitwarden,
The **Item ID** should be auto-populated (reading from the DB
**Name** of the Item ( Google, my application...)
**Folder**, to be able to select from the existent folders 
and so on.

**Comment by quinone** [comment]
Great, so it can be cut down to : 
* ID(auto-incremented),
* Name, 
* Username, 
* Password, 
* Note
* URI

**Comment by Pitoche** [comment]
If you think they are not used anywhere.....  I was just pointing out my understanding of why those fields exist not going into details. But the DB has changed since the day I created it initially.  
Can we distribute the tasks amongst us? I am happy with whatever area(s). I started the UI. but, I'm happy with anything,

**Comment by quinone** [comment]
Completed
